export type Employee = {
    id: number;
    FullName: string;
    EmpNbr: string;
    FirstName: string;
    LastName: string;
    MidName: string;
    Suffix: string;
    Address: string;
    CityProv: string;
    Position: string;
    Assignment: string;
    SalaryGrade: string;
    BirthDate: string;
    EmployDate: string;
    RegularDate: string;
    ResignDate: string;
    BasicPay: number;
    DailyRate: number;
    HourlyRate: number;
    Status: boolean;
    SSSNbr: string;
    PHICNbr: string;
    HDMFNbr: string;
    TIN: string;
    Degree: string;
    AllowReg: number;
    BPIATM: string;
    BPIEmpCode: string;
    PIN: string;
    PERAAID: string;
    Group: string;
    BiometricID?: string;
    Image?: string | null;
    ImageUrl: string | null;
    GroupName?: string;
    // Schedule?: Schedule[];
    // ScheduleTemplate?: ScheduleTemplate[];
};
